packageName: Ravi.Web.Api
classModifier: abstract
operationModifier: abstract
operationResultTask: true
OperationIsAsync: true
useNewtonsoft: true
sourceFolder: ""
enumValueSuffix: ""
useDateTimeOffset: true
nullableReferenceTypes: true
useSwashbuckle: false
useDateTimeForDate: true